import enLocale from 'element-ui/lib/locale/lang/en';

const en = {
  log_in: 'Login',
  register: 'Register',
  FistRegister: 'Register',
  AutoFill: 'Auto Fill',
  ForgetPassword: 'Forget oassword',
  inputVcode: 'Please enter verify code',
  PleaseFillInYourEmailAddress: 'Please fill in your email address',
  PleaseFillInYourPassword: 'Please fill in your password',
  initPage: 'Home',
  inbound: 'Inbound',
  outbound: 'Outbound',
  inventory: 'Inventory',
  shops: 'Shop',
  setting: 'Setting',
  home: 'Home',
  help: 'Help',
  goodsAdd: 'Add product',
  addInbound: 'Add inbound',
  addOutbound: 'Add outbound',
  inventoryManage: 'Inventory',
  storeManage: 'Warehouse',
  shopsManagement: 'Shops',
  inboundList: 'Inbound list',
  outboundList: 'Outbound list',
  email: 'Email',
  nick_name: 'Nick name',
  avatar: 'Avatar',
  confirm: 'Confirm',
  Back: 'Back',
  inventoryAlarm: 'Inventory alarm',
  stockTaking: 'Stock taking',
  addressManagement: 'Address',
  supplierManagement: 'Supplier',
  categoryManagement: 'Category',
  record: '出入库单分类',
  ChangePassword: 'Change password',
  oldPassword: 'Old Password',
  newPassword: 'New Password',
  addWarehouse: 'Add warehouse',
  inputPsw: 'Please enter password',
  OrderCode: '单据编号',
  Status: 'Status',
  Type: 'Type',
  supplier: 'Supplier',
  planNumber: 'Estimate Number',
  realityNumber: 'Reality  Number',
  createdTime: 'Created time',
  editRecevier: "Edit Recevier's Information",
  operation: 'Operation',
  detail: 'Detail',
  inboundAndShelf: 'InboundAndShelf',
  delete: 'Delete',
  startDate: 'Start Date',
  endDate: 'End Date',
  InboundListType: 'Inbound Tag',
  inboundstatus: 'Inbound Status',
  DRK: 'waiting',
  RKWC: 'success',
  Essentialformrmation: 'Basic lnformation',
  Pleseselectsupplier: 'Please select supplier',
  category: 'Category',
  inboundNumbers: 'Inbound Number',
  notNecessaryInfo: 'Optional Information',
  remark: 'Remark',
  outboundNumber: 'Outbound Number',
  expressOrder: 'Express Order',
  outboundType: 'Type',
  orderSources: 'Order Sources',
  CreateTime: 'Create Time',
  Search: 'Search',
  cancelOrder: 'Cancel',
  cancel: 'Cancel',
  DDBQX: '订单被取消',
  DJH: '待确认',
  JHZ: '待发货',
  PSZ: '配送中',
  YSH: '已签收',
  name: 'Name',
  phone: 'Phone',
  SSQ: '省市区',
  addressDetial: 'Address Detial',
  submit: 'Submit',
  cnName: 'Name',
  enName: '外文名称',
  Number: 'Number',
  address: 'Address',
  edit: 'Edit',
  sender: '发件人',
  receiver: '收件人',
  Welcome: 'Welcome to Use Cangmishu WMS',
  WelcomeText: 'The Cangmishu Wms is Free Software for WarehouseProvide you with a free, professional Internet warehouse + order management solution',
  accountWords: 'Password',
  wechat: 'Wechat Scan',
  scanWechatQR: 'No need to register, WeChat scan code to log in',
  EmailRegister: 'Email Register',
  MobileReister: 'Mobile Reister',
  Sendtheverificationcode: 'Send the verification code',
  IHaveAnAccount: 'I have an account',
  PleaseEnterCaptchaCode: 'Please Enter Captcha Code',
  PleaseEnterMoblieNumber: 'Please Enter Moblie Number',
  theUserAgreement: 'the user agreement',
  IAgree: 'I agree',
  SetupNewPassword: 'Setup New Password',
  PswAgain: 'Please enter your password again',
  EmailInput: ' Please enter email',
  SendEmail: 'Send Email',
  BackToLoginPage: ' Back To Login Page',
  OutBoundToday: 'OutBound Today',
  InBoundToday: 'InBound Today',
  StockQty: 'Stock Qty',
  OutBoundThisMonth: 'OutBound This Month',
  InBoundThisMonth: 'InBound This Month',
  Numbers: 'Number',
  PleaseEnterNumber: 'Please Enter Number',
  goodsorder: 'List',
  goodsList: 'List',
  pleaseSelect: 'Select Product Spec',
  mustEnter: ' * is required',
  specName: 'Spec Name',
  PurcharsePrice: 'Purcharse Price',
  distributorManagement: 'Supplier',
  distributorName: 'Supplier',
  add: 'Add',
  AcrionTips: 'This action will delete it permanently, sure to continue?',
  areaAndShelf: '货区和货位',
  // 以上仓秘书
  ...enLocale,
};

export default en;
