import enLocale from 'element-ui/lib/locale/lang/en';

const en = {
  log_in: 'Login',
  register: 'Register',
  FistRegister: 'Register',
  AutoFill: 'Auto Fill',
  ForgetPassword: 'Forget oassword',
  inputVcode: 'Please enter verify code',
  PleaseFillInYourEmailAddress: 'Please fill in your email address',
  PleaseFillInYourPassword: 'Please fill in your password',
  initPage: 'Home',
  inbound: 'Inbound',
  outbound: 'Outbound',
  inventory: 'Inventory',
  shops: 'Shop',
  setting: 'Setting',
  contactus: 'Contact Us',
  tips2: 'Any Question please use wechat scan the qrcode',
  ApiDoucment: 'Api Doucment',
  home: 'Home',
  help: 'Help',
  helpCenter: 'Help Center',
  goodsAdd: 'Add product',
  addInbound: 'Add inbound',
  addOutbound: 'Add outbound',
  inventoryManage: 'Inventory',
  storeManage: 'Warehouse',
  shopsManagement: 'Shops',
  shopLogoUpload: 'Upload Logo',
  productImage: 'Image',
  ProductName2: 'Name',
  sale: 'Selling price',
  time: 'Time',
  PutOn: 'Put On',
  PutOff: 'Put Off',
  Batchoperation: 'Batch operation',
  GoodsCarouselFigure: 'Goods Carousel Figure',
  uploadImage: 'Upload',
  goodsIntroduction: 'Introduction',
  inboundList: 'Inbound list',
  outboundList: 'Outbound list',
  email: 'Email',
  nick_name: 'Nick name',
  avatar: 'Avatar',
  confirm: 'Confirm',
  Back: 'Back',
  inventoryAlarm: 'Inventory alarm',
  stockTaking: 'Stock taking',
  addressManagement: 'Address',
  supplierManagement: 'Supplier',
  categoryManagement: 'Category',
  goodsSpecification: 'Product Measurement',
  addASpecification: 'Add a specification',
  addLine: 'Add a Line',
  bestUseTime: 'Best before date',
  Expirydate: 'Expiry date',
  ProductionBatch: 'Production batch',
  record: '出入库单分类',
  ChangePassword: 'Change password',
  oldPassword: 'Old Password',
  newPassword: 'New Password',
  addWarehouse: 'Add warehouse',
  inputPsw: 'Please enter password',
  OrderCode: 'NO',
  addStocktaking: 'Add Stocktaking',
  addCheckStock: 'Add Stocktaking',
  stockTakingList: 'List',
  stocktalkingName: 'Name',
  ProductName: 'Name',
  ExportProductinventory: 'Export inventory',
  Status: 'Status',
  Type: 'Type',
  supplier: 'Supplier',
  planNumber: 'Estimate Number',
  realityNumber: 'Reality  Number',
  createdTime: 'Created time',
  editRecevier: "Edit Recevier's Information",
  operation: 'Operation',
  detail: 'Detail',
  checkStockPre: 'Preview',
  download: 'Download',
  inboundAndShelf: 'InboundAndShelf',
  delete: 'Delete',
  startDate: 'Start Date',
  endDate: 'End Date',
  ExportProductList: 'Product List',
  warningEmail: 'Warning Email',
  InboundListType: 'Inbound Tag',
  inboundstatus: 'Inbound Status',
  Contactformrmation: 'Contact Info',
  shopAdd: 'Add Shop',
  shopName: 'Name',
  shopQR: 'QR Code',
  shopLogo: 'Logo',
  storeGoods: 'Goods Mangement',
  shopIntroduction: 'Introduction',
  shopInformation: 'Information',
  shopOwner: 'Owner',
  DRK: 'waiting',
  RKWC: 'success',
  Essentialformrmation: 'Basic lnformation',
  Pleseselectsupplier: 'Please select supplier',
  category: 'Category',
  inboundNumbers: 'Inbound Number',
  notNecessaryInfo: 'Optional Information',
  remark: 'Remark',
  outboundNumber: 'Outbound Number',
  expressOrder: 'Express Order',
  outboundType: 'Type',
  orderSources: 'Order Sources',
  CreateTime: 'Create Time',
  Search: 'Search',
  cancelOrder: 'Cancel',
  cancel: 'Cancel',
  DDBQX: '订单被取消',
  DJH: '待确认',
  JHZ: '待发货',
  PSZ: '配送中',
  YSH: '已签收',
  name: 'Name',
  phone: 'Phone',
  SSQ: '省市区',
  addressDetial: 'Address Detial',
  submit: 'Submit',
  cnName: 'Name',
  enName: '外文名称',
  Number: 'Number',
  address: 'Address',
  addGoods: 'Add Goods',
  basicSetting: 'Basic Setting',
  commodityClassificationManage: 'Add Category',
  SKUProperty: 'SKU Properties',
  categoryNameCN: 'Chinese Name',
  categoryNameEN: 'English Name',
  dateTips: 'Turn on this option, all the goods below the category need to fill in the shelf life, the outbound will be shipped from near to far according to the expiration date of the product.',
  patchTips: 'Turn on this option, all the goods below the category need to fill in the production batch, so that you can find the batch information of each outbound when you go out.',
  goodsTips: 'Turn on this option, all the goods below the category need to fill in the best consumption period, mainly used in the food industry.',
  edit: 'Edit',
  sender: 'Sender',
  receiver: 'Receiver',
  addsender: 'Add Sender',
  addreceiver: 'Add Receiver',
  addsupplier: 'Add Supplier',
  supplierNameCN: 'Name(CN)',
  Welcome: 'Welcome to Use Cangmishu WMS',
  WelcomeText: 'The Cangmishu Wms is Free Software for WarehouseProvide you with a free, professional Internet warehouse + order management solution',
  accountWords: 'Password',
  wechat: 'Wechat Scan',
  scanWechatQR: 'No need to register, WeChat scan code to log in',
  EmailRegister: 'Email Register',
  MobileReister: 'Mobile Reister',
  Sendtheverificationcode: 'Send the verification code',
  IHaveAnAccount: 'I have an account',
  PleaseEnterCaptchaCode: 'Please Enter Captcha Code',
  PleaseEnterMoblieNumber: 'Please Enter Moblie Number',
  theUserAgreement: 'the user agreement',
  IAgree: 'I agree',
  SetupNewPassword: 'Setup New Password',
  PswAgain: 'Please enter your password again',
  EmailInput: ' Please enter email',
  SendEmail: 'Send Email',
  BackToLoginPage: ' Back To Login Page',
  OutBoundToday: 'OutBound Today',
  InBoundToday: 'InBound Today',
  StockQty: 'Stock Qty',
  OutBoundThisMonth: 'OutBound This Month',
  InBoundThisMonth: 'InBound This Month',
  Numbers: 'Number',
  PleaseEnterNumber: 'Please Enter Number',
  goodsorder: 'List',
  goodsList: 'List',
  pleaseSelect: 'Select Product Spec',
  mustEnter: ' * is required',
  specName: 'Spec Name',
  PurcharsePrice: 'Purcharse Price',
  distributorManagement: 'Supplier',
  distributorName: 'Supplier',
  add: 'Add',
  AcrionTips: 'This action will delete it permanently, sure to continue?',
  areaAndShelf: 'Area & LOcation',
  PleaseSelectCategory: 'Please Select Category',
  PleaseEnterAKeyword: 'Please enter a keyword',
  AddProduct: 'Add Product',
  AllCartory: 'All',
  NO: 'NO.',
  ProductSpec: 'Product & Spec',
  PurchasePrice: 'Purchase Price',
  SalePrice: 'Sale Price',
  Stock: 'Stock',
  CangmishuWMS: 'Cangmishu WMS ',
  OrdinaryOutboundOrder: 'Ordinary Outbound Order',
  warehouse: 'Warehouse',
  goodsDetial: 'Goods Detial',
  goodsName: 'Name',
  OrderQty: 'Order Qty',
  ConfirmQty: 'Confirm Qty',
  Date: 'Date',
  Shipping: 'Shipping (Option)',
  Tracking: 'Tracking No.(Option)',
  Payment: 'Payment',
  PayStatus: 'Pay Status',
  Paid: 'Paid',
  No: 'No.',
  Inboundtimes: 'Inbound times',
  Outboundtimes: 'Outbound times',
  InboundItemnumber: 'Inbound Item number',
  OutboundItemnumber: 'Outbound Item number',
  DataAnalysis: 'Data Analysis',
  warehouseStock: 'Stock ',
  StockCheck: 'Stock Check',
  Location: 'Location',
  StockHistory: 'Stock History',
  Inboundtimesnumbers: 'Inbound times / numbers',
  Outboundtimesnumbers: 'Outbound times / numbers',
  OperationNumber: 'Operation Number',
  Operationdate: 'Operation date',
  OrderNumber: 'Order Number',
  TotalInventory: 'Total Inventory',
  day: 'Day',
  month: 'Month',
  year: 'Year',
  ProductData: 'Product',
  OutboundData: 'Outbound',
  Todo: 'Todo',
  Warning: 'Warning',
  UnShelf: 'UnShelf',
  UnConfirm: 'UnConfirm:',
  OrderWechatMiniProgramDemo: 'Order Wechat Mini Program Demo',
  FreetogetWechatMiniProgram: 'Free to get Wechat Mini Program',
  WechatOfficialAccount: 'Wechat  Official Account',
  AnyQuestionletmeknow: 'Any Question let me know',
  TheFieldmaynotbegreaterthan30characters: 'The Field may not be greater than 30 characters',
  TheFieldmaynotbegreaterthan50characters: 'The Field may not be greater than 50 characters',
  goodsImageDetial: 'Details figure',
  Export: 'Export',
  Currency: 'Currency',
  CNY: 'CNY(￥)',
  EUR: 'EUR(€)',
  USD: 'USD($)',
  OutboundQuantity: 'Outbound Quantity',
  OutboundDate: 'Outbound Date',
  outboundTips: 'Using the Edit Logistics function, the order status will be changed (to be shipped --> in delivery)',
  CheckOrder: 'Check Order',
  PrintPicking: 'Print Picking',
  Track: 'Track',
  Paid2: 'Paid',
  Trace: 'Trace',
  Signing: 'Signing',
  Submit: 'Submit',
  EditTrack: 'Edit',
  DeliveryCompany: 'delivery company',
  TrackingNumber: 'Tracking Number',
  tips: 'Tips',
  checkTips: 'Are you sure ?',
  outboundDetial: 'Detial',
  downloadOutbound: 'Download',
  selectStatus: 'Please select status',
  planOutboundTime: 'Plan Time',
  pleaseEnterOutboundNO: 'Please Enter Outbound Number',
  EstimatedOutboundDate: 'Estimated Outbound Date',
  DateMust: 'The Date is required',
  success: 'Success !',
  ProductTAG: 'Product TAG',
  OrderItems: 'Order Items',
  info: 'Information',
  From: 'From',
  To: 'To',
  selectReceiver: 'Select',
  selectSender: 'Select',
  outboundLists: 'Outbound List',
  selectGoods: 'Select',
  pleaseSelectProductSpec: 'Please Select Product Spec',
  SalePrice1: 'Sale Price',
  Belowstock: 'Below stock',
  addGoods1: 'Add Goods',
  downloadtemplate: 'Download template',
  importproductlist: 'Import product list',
  LastUpdated: 'Last Updated',
  GoodsManage: 'Goods Manage',
  specificationChineseName: 'Measurement In Chinese',
  specificationEnglishName: 'Measurement In English',
  remove: 'Remove',
  EssentialInformation: 'Basic lnformation',
  SizeName: 'Name',
  grossWeight: 'Gross Weight (g)',
  pictureNoLargerThan2M: 'Picture no larger than 2M in jpg png or jpeg format',
  pleaseEnterSKU: 'Please Enter SKU',
  PleaseEnterGram: 'Please enter gram',
  inputCnWord: 'Please enter chinese product name',
  checkSku: 'Are you sure ?',
  productCodeBlank: 'Please enter product code',
  SpecificationName: 'Specification cannot be empty',
  editSuccess: 'Success !',
  addSuccess: 'Success !',
  goodsRemark: 'Goods Remark',
  goodsPhoto: 'Goods Photo',
  enterspecificationChineseName: 'Please Enter Specification Chinese Name*',
  enterspecificationEnglishName: 'Please Enter Specification English Name*',
  pleaseEnterSpecificationName: 'Please Enter Specification Name',
  warehouseNO: 'NO',
  storeName: 'Name',
  WarehouseArea: 'Area(㎡)',
  warehouseConfig: 'Configuration',
  setDefault: 'Set default',
  AreaCode: 'Code',
  AreaName: 'Section',
  AreaFunction: 'Function',
  AreaTag: 'Tag',
  AreaStatus: 'Status',
  ReceiptCategoryName: 'Inbound Tag Name(CN)',
  DeliveryListcategoryname: 'Outbound Tag Name(CN)',
  addBatchType: 'Add Inbound Tag',
  addOrderType: 'Add Outbound Tag',
  BatchName: 'Name',
  orderName: 'Name',
  AreaOperate: 'Operation',
  ShelfCode: 'Code',
  ShelfArea: 'Section',
  ShelfCapacity: 'Capacity（m³）',
  ShelfStatus: 'Status',
  ShelfOperation: 'Operation',
  addCargoShelf: 'Add Rack Information',
  BasketCode: 'Code',
  BasketCapacity: 'Capacity（m³）',
  Capacity: 'Capacity（m³）',
  BasketCapacityWeight: 'Weight（g）',
  BasketStatus: 'Status',
  Section: 'Section',
  BelongingArea: 'Section',
  Rack: 'Rack',
  addCargoArea: 'Add CargoArea Information',
  editCargoArea: 'Edit CargoArea Information',
  ShippingAreaNumber: 'Code',
  ShippingAreaName: 'Name',
  WhetherToEnable: 'In use',
  pleaseEnterShippingAreaNumber: 'Please Enter Area Number',
  pleaseEnterShippingAreaName: 'Please Enter Area Name',
  checkStockGoods: 'Goods',
  checkStockStatus: 'Status',
  checkStockDate: 'Date',
  aisle: 'Aisle',
  row: 'Row',
  Columns: 'Columns',
  Floor: 'Layer',
  pleaseEnterCapacity: 'Please enter capacity',
  PleaseSelectTheTargoarea: 'Plese select section',
  editCargoShelf: 'Edit Rack Information',
  ...enLocale,
};
export default en;
