import enLocale from 'element-ui/lib/locale/lang/en';

const en = {
  log_in: 'Login',
  register: 'Register',
  FistRegister: 'Register',
  AutoFill: 'Auto Fill',
  ForgetPassword: 'Forget password',
  ChangePassword: 'Change Password',
  LogOut: 'Log Out',
  SwitchWarehouse: 'Select Warehouse',
  profile: 'Profile',
  upload: 'Upload',
  checkedWh: 'Please select warehouse',
  inputVcode: 'Please enter verify code',
  PleaseFillInYourEmailAddress: 'Please fill in your email address',
  PleaseFillInYourPassword: 'Please fill in your password',
  initPage: 'Home',
  inbound: 'Inbound',
  outbound: 'Outbound',
  inventory: 'Inventory',
  shops: 'Shop',
  setting: 'Setting',
  contactus: 'Contact Us',
  tips2: 'Any Question please use wechat scan the qrcode',
  ApiDoucment: 'Api Doucment',
  home: 'Home',
  help: 'Help',
  helpCenter: 'Help Center',
  goodsAdd: 'Add product',
  addInbound: 'Add inbound',
  addOutbound: 'Add outbound',
  inventoryManage: 'Inventory',
  storeManage: 'Warehouse',
  imagePreview: 'Preview',
  nomorethan3: ' Maximum 3 pictures,suggested size 400*400',
  nomorethan4: 'Maximum 10 pictures, suggested size 400*400',
  shoptips: 'You can create a warehouse-specific applet by adding a shop. After you create a shop, you can synchronize the goods in the warehouse to your applet. The user can directly generate the goods outbound order through the applet. In the warehouse business, there is no need to manually place order, and use the applet to place an order to create outbound order. (A warehouse can generate multiple shop applets!)',
  addGoodsTips: 'This will leave the current page, will you continue?',
  shopsManagement: 'Shop List',
  shopLogoUpload: 'Upload Logo',
  AddingProduct: 'Adding product category will leave the current page, OK?',
  Pleaseentersuppliername: 'Please enter supplier name',
  Themailhasbeensent: 'The mail has been sent, please check it',
  productImage: 'Image',
  ProductName2: 'Name',
  sale: 'Selling price',
  time: 'Time',
  PutOn: 'Put On',
  PutOff: 'Put Off',
  Batchoperation: 'Batch operation',
  GoodsCarouselFigure: 'Product Carousel Figure',
  uploadImage: 'Upload',
  goodsIntroduction: 'Introduction',
  inboundList: 'Inbound list',
  outboundList: 'Outbound list',
  email: 'Email',
  nick_name: 'Nick name',
  avatar: 'Avatar',
  confirm: 'Confirm',
  Back: 'Back',
  inventoryAlarm: 'Stock Alert',
  SKUTips: 'SKU是商品唯一编码，保存后不能更改，且不能重复',
  stockTaking: 'Stock taking',
  addressManagement: 'Address',
  supplierManagement: 'Supplier',
  categoryManagement: 'Category',
  goodsSpecification: 'Product Measurement',
  addStoreManage: 'Create Warehouse',
  WarehouseList: 'Warehouse List',
  CurrentLanguage: 'Current Language:',
  warehouse: 'Warehouse',
  selectdWh: 'Select Warehouse',
  addASpecification: 'Add a specification',
  addLine: 'Add a Line',
  bestUseTime: 'Best before date',
  Pleaseselectrack: 'Please select rack',
  PleaseenterEAN: 'Please enter EAN',
  PleaseEnterPhone: 'Please enter phone',
  Pleaseselectexpirydate: 'Please select expiry date',
  Pleaseenterproductionbatch: 'Please enter production batch',
  Pleaseselectbestbeforedate: 'Please select best before date',
  Thiswillleavethecurrentpagewillyoucontinue: 'This will leave the current page, will you continue?',
  Pleasecompletetheform: 'Please complete the form',
  OutboundTag: 'Outbound Tag',
  moreRack: 'More',
  Expirydate: 'Expiry date',
  ProductionBatch: 'Production batch',
  record: 'Out/In Tag',
  oldPassword: 'Old Password',
  newPassword: 'New Password',
  addWarehouse: 'Add warehouse',
  inputPsw: 'Please enter password',
  OrderCode: 'NO',
  addStocktaking: 'Add Stocktaking',
  addCheckStock: 'Add Stocktaking',
  stockTakingList: 'List',
  stocktalkingName: 'Name',
  save: 'Save',
  ProductName: 'Name',
  Chinesespecifications: 'Measurement',
  tipsSku: 'SKU is the unique code of goods. It cannot be changed after saving and cannot be repeated.',
  ExportProductinventory: 'Export inventory',
  Status: 'Status',
  Type: 'Type',
  supplier: 'Supplier',
  planNumber: 'Expected Quantity',
  realityNumber: 'Inbound Quantity',
  inboundShelf: 'Putaway',
  PleaseenterorscanSKU: 'Please enter or scan SKU',
  createdTime: 'Created time',
  editRecevier: "Edit Recevier's Information",
  operation: 'Operation',
  detail: 'Detail',
  checkStockPre: 'Preview',
  download: 'Download',
  inboundAndShelf: 'Putaway',
  delete: 'Delete',
  startDate: 'Start Date',
  endDate: 'End Date',
  ExportProductList: 'Product List',
  warningEmail: 'Alert  Email',
  PleaseenterEmail: 'Please enter Email',
  MinimumInventory: 'Minimum Inventory',
  InboundListType: 'Inbound Tag',
  inboundstatus: 'Inbound Status',
  Contactformrmation: 'Contact Info',
  shopAdd: 'Add Shop',
  shopName: 'Name',
  shopQR: 'QR Code',
  shopLogo: 'Logo',
  storeGoods: 'Product Mangement',
  shopIntroduction: 'Introduction',
  shopInformation: 'Information',
  shopOwner: 'Owner',
  DRK: 'waiting',
  RKWC: 'success',
  Essentialformrmation: 'Basic lnformation',
  Pleseselectsupplier: 'Please select supplier',
  category: 'Category',
  inboundNumbers: 'Inbound Number',
  notNecessaryInfo: 'Optional Information',
  OptionalInformation: 'Optional Information',
  remark: 'Remark',
  outboundNumber: 'Outbound Number',
  expressOrder: 'Express Order',
  outboundType: 'Type',
  orderSources: 'Order Sources',
  CreateTime: 'Create Time',
  Search: 'Search',
  cancelOrder: 'Cancel',
  cancel: 'Cancel',
  DDBQX: '订单被取消',
  DJH: '待确认',
  JHZ: '待发货',
  PSZ: '配送中',
  YSH: '已签收',
  name: 'Name',
  phone: 'Phone',
  SSQ: 'City',
  addressDetial: 'Address',
  pleaseInputCity: 'Please enter city',
  Pleaseenteradetailedaddress: 'Please enter a detailed address',
  Pleaseenterawarehousename: 'Please enter the name of the warehouse',
  Pleaseenterapositiveinteger: 'Please enter a positive integer',
  submit: 'Submit',
  cnName: 'Name',
  enName: '外文名称',
  Number: 'Number',
  address: 'Address',
  addGoods: 'Add Product',
  Pleasetypeinyourname: 'Please type in your name',
  basicSetting: 'Basic Setting',
  commodityClassificationManage: 'Add Category',
  SKUProperty: 'SKU Properties',
  categoryName: 'Category Name',
  categoryNameCN: 'Category Name',
  categoryNameEN: 'Category Name',
  Pleaseentercategoryname: 'Please enter category name',
  Category: 'Category',
  extraInfomation: 'More',
  PleaseEnterTheWarehouseArea: 'Warehouse area is required',
  PleaseEnterTheMailbox: 'Please enter your email or phone number',
  dateTips: 'Turn on this option, all the goods below the category need to fill in the shelf life, the outbound will be shipped from near to far according to the expiration date of the product.',
  patchTips: 'Turn on this option, all the goods below the category need to fill in the production batch, so that you can find the batch information of each outbound when you go out.',
  goodsTips: 'Turn on this option, all the goods below the category need to fill in the best consumption period, mainly used in the food industry.',
  Estimatednumberofwarehousing: 'Expected Quantity',
  Actualwarehousingquantity: 'Inbounded Quantity',
  Inboundbatchnumber: 'Inbound batch',
  Numberofpreloaded: 'Expected Quantity',
  ProductnameorSKU: 'Product name or SKU',
  BoxCode: 'Box Code',
  EANCode: 'EAN Code',
  ExpiryDate: 'Expiry Date',
  Pleaseselectdate: 'Please select date',
  edit: 'Edit',
  sender: 'Sender',
  receiver: 'Receiver',
  addsender: 'Add Sender',
  addreceiver: 'Add Receiver',
  addsupplier: 'Add Supplier',
  setOutbound: 'Check Order',
  Ordercancelled: 'Order cancelled',
  Tobeconfirmed: 'To be confirmed',
  Tobedelivered: 'To be delivered',
  Delivery: 'On the road',
  Received: 'Received',
  supplierNameCN: 'Name',
  Welcome: 'Welcome to Use Cangmishu WMS',
  WelcomeText: 'The Cangmishu Wms is Free Software for WarehouseProvide you with a free, professional Internet warehouse + order management solution',
  accountWords: 'Password',
  wechat: 'Wechat Scan',
  scanWechatQR: 'No need to register, WeChat scan code to log in',
  EmailRegister: 'Email Register',
  MobileReister: 'Mobile Reister',
  Sendtheverificationcode: 'Send the verification code',
  IHaveAnAccount: 'I have an account',
  PleaseEnterCaptchaCode: 'Please Enter Captcha Code',
  PleaseEnterMoblieNumber: 'Please Enter Moblie Number',
  theUserAgreement: 'the user agreement',
  Pleaseenterthecorrectmobilephonenumber: 'Please enter the correct mobile phone number',
  IAgree: 'I agree',
  PleaseEnterTheContactEmails: 'Please Enter The Contact Emails',
  SetupNewPassword: 'Setup New Password',
  PswAgain: 'Please enter your password again',
  EmailInput: ' Please enter email',
  SendEmail: 'Send Email',
  BackToLoginPage: ' Back To Login Page',
  OutBoundToday: 'OutBound Today',
  InBoundToday: 'InBound Today',
  StockQty: 'Stock Qty',
  OutBoundThisMonth: 'OutBound This Month',
  InBoundThisMonth: 'InBound This Month',
  Numbers: 'Number',
  PleaseEnterNumber: 'Please Enter Number',
  goodsorder: 'List',
  goodsList: 'List',
  pleaseSelect: 'Select Product Spec',
  mustEnter: ' * is required',
  specName: 'Spec Name',
  PurcharsePrice: 'Purcharse Price',
  distributorManagement: 'Supplier',
  distributorName: 'Supplier',
  LogoutTips: ' Are you sure ?',
  add: 'Add',
  AcrionTips: 'This action will delete it permanently, sure to continue?',
  areaAndShelf: 'Section&Rack',
  PleaseSelectCategory: 'Please Select Category',
  PleaseEnterAKeyword: 'Please enter a keyword',
  AddProduct: 'Add Product',
  AllCartory: 'All',
  NO: 'NO.',
  ProductSpec: 'Product & Spec',
  PurchasePrice: 'Purchase Price',
  SalePrice: 'Sale Price',
  Stock: 'Stock',
  CangmishuWMS: 'Cangmishu WMS ',
  planInboundTime: 'Inbound Time',
  OrdinaryOutboundOrder: 'Ordinary Outbound Order',
  goodsDetial: 'Product Detail',
  goodsName: 'Name',
  OrderQty: 'Order Qty',
  ConfirmQty: 'Confirm Qty',
  viewInboundList: 'Details',
  Inbound: 'Inbound',
  DownloadInbound: 'Download',
  DownloadPurchaseOrder: 'Download',
  PurchaseOrder: 'Purchase Order',
  DondownLoadInboundbatchnumber: 'Download',
  printTips: '70mm*50mm label paper is recommended for printing',
  Date: 'Date',
  Shipping: 'Shipping (Option)',
  Tracking: 'Tracking No.(Option)',
  Payment: 'Payment',
  PayStatus: 'Pay Status',
  Paid: 'Paid',
  No: 'No.',
  Inboundtimes: 'Inbound times',
  Outboundtimes: 'Outbound times',
  InboundItemnumber: 'Inbound Item number',
  OutboundItemnumber: 'Outbound Item number',
  DataAnalysis: 'Data Analysis',
  warehouseStock: 'Stock ',
  StockCheck: 'Stock Check',
  Location: 'Location',
  StockHistory: 'Stock History',
  Inboundtimesnumbers: 'Inbound times / numbers',
  Outboundtimesnumbers: 'Outbound times / numbers',
  OperationNumber: 'Operation Number',
  Operationdate: 'Operation date',
  OrderNumber: 'Order Number',
  TotalInventory: 'Total Inventory',
  day: 'Day',
  month: 'Month',
  year: 'Year',
  ProductData: 'Product',
  OutboundData: 'Outbound',
  Todo: 'Todo',
  Warning: 'Warning',
  UnShelf: 'UnShelf',
  UnConfirm: 'UnConfirm:',
  OrderWechatMiniProgramDemo: 'Order Wechat Mini Program Demo',
  FreetogetWechatMiniProgram: 'Free to get Wechat Mini Program',
  WechatOfficialAccount: 'Wechat  Official Account',
  AnyQuestionletmeknow: 'Any Question let me know',
  TheFieldmaynotbegreaterthan30characters: 'The Field may not be greater than 30 characters',
  TheFieldmaynotbegreaterthan50characters: 'The Field may not be greater than 50 characters',
  goodsImageDetial: 'Details figure',
  Export: 'Export',
  Currency: 'Currency',
  CNY: 'CNY(￥)',
  EUR: 'EUR(€)',
  USD: 'USD($)',
  OutboundQuantity: 'Outbound Quantity',
  OutboundDate: 'Outbound Date',
  outboundTips: 'Using the Edit Logistics function, the order status will be changed (to be shipped --> in delivery)',
  CheckOrder: 'Check Order',
  PrintPicking: 'Print Picking',
  Whethertheshelf: 'Whether the shelf',
  Track: 'Track',
  Paid2: 'Paid',
  Trace: 'Trace',
  Signing: 'Signing',
  Submit: 'Are you sure confirm',
  EditTrack: 'Edit Tracking',
  DeliveryCompany: 'Delivery company',
  TrackingNumber: 'Tracking Number',
  Pleaseselect: 'Please select',
  tips: 'Tips',
  checkTips: 'Are you sure ?',
  outboundDetial: 'Detail',
  downloadOutbound: 'Download',
  selectStatus: 'Please select status',
  planOutboundTime: 'Plan Time',
  pleaseEnterOutboundNO: 'Please Enter Outbound Number',
  EstimatedOutboundDate: 'Estimated Outbound Date',
  DateMust: 'The Date is required',
  success: 'Success !',
  ProductTAG: 'Category',
  OrderItems: 'Order Items',
  info: 'Information',
  From: 'From',
  To: 'To',
  selectReceiver: 'Select',
  selectSender: 'Select',
  outboundLists: 'Outbound List',
  selectGoods: 'Select',
  pleaseSelectProductSpec: 'Please Select Product Spec',
  SalePrice1: 'Sale Price',
  Belowstock: 'Below stock',
  addGoods1: 'Add Product',
  downloadtemplate: 'Download template',
  importproductlist: 'Import product list',
  LastUpdated: 'Last Updated',
  GoodsManage: 'Product Manage',
  specificationChineseName: 'Measurement Name',
  specificationEnglishName: 'Measurement In English',
  remove: 'Remove',
  EssentialInformation: 'Basic lnformation',
  SizeName: 'Name',
  grossWeight: 'Gross Weight (g)',
  pictureNoLargerThan2M: 'Picture no larger than 2M in jpg png or jpeg format',
  pleaseEnterSKU: 'Please Enter SKU',
  PleaseEnterGram: 'Please enter gram',
  inputCnWord: 'Please ente product name',
  PleaseInputApassword: 'Please enter password',
  checkSku: 'Are you sure ?',
  productCodeBlank: 'Please enter product code',
  SpecificationName: 'Specification cannot be empty',
  productName: 'Product Name',
  editSuccess: 'Success !',
  addSuccess: 'Success !',
  goodsRemark: 'Product Remark',
  goodsPhoto: 'Product Photo',
  enterspecificationChineseName: 'Please Enter Specification Chinese Name*',
  enterspecificationEnglishName: 'Please Enter Specification English Name*',
  pleaseEnterSpecificationName: 'Please Enter Specification Name',
  warehouseNO: 'NO.',
  yes: 'ON',
  no: 'OFF',
  TheCaptchaCannotBeEmpty: 'verification code must be filled',
  Passwordcannotbeempty: 'Password cannot be empty',
  Theverificationcodemustbeasixdigitnumber: 'The verification code must be a six-digit number.',
  Passwordisatleast6characters: 'Password is at least 6 characters',
  Warehousenamecannotbeempty: 'Warehouse name cannot be empty',
  Warehouseareacannotbeempty: 'Warehouse area cannot be empty',
  Warehouseareacanonlybenumeric: 'Warehouse area can only be numeric.',
  Sendsuccessfullypleasecheck: 'Send successfully, please check!',
  storeName: 'Warehouse Name',
  Useragreementrequired: 'User agreement required',
  Registrationsuccessful: 'Registration successful',
  WarehouseArea: 'Area(㎡)',
  warehouseConfig: 'Configuration',
  setDefault: 'Set default',
  AreaCode: 'Code',
  AreaName: 'Section',
  AreaFunction: 'Function',
  AreaTag: 'Tag',
  AreaStatus: 'Status',
  ReceiptCategoryName: 'Inbound Tag',
  Pleaseenterinboundtagname: 'Please enter tag name',
  DeliveryListcategoryname: 'Outbound Tag',
  addBatchType: 'Add Inbound Tag',
  addOrderType: 'Add Outbound Tag',
  BatchName: 'Name',
  orderName: 'Name',
  AreaOperate: 'Operation',
  PleasescanrackorSKUorinboundbatch: 'Please scan rack or SKU or inbound batch',
  CurrentStock: 'Current Stock',
  ShelfCode: 'Code',
  ShelfArea: 'Section',
  ShelfCapacity: 'Capacity（m³）',
  ShelfStatus: 'Status',
  ShelfOperation: 'Operation',
  addCargoShelf: 'Add Rack Information',
  Originalstock: 'Original Stock',
  InventoryCount: 'Inventory Count',
  BasketCode: 'Code',
  BasketCapacity: 'Capacity（m³）',
  Capacity: 'Capacity（m³）',
  BasketCapacityWeight: 'Weight（g）',
  BasketStatus: 'Status',
  Section: 'Section',
  BelongingArea: 'Section',
  Rack: 'Rack',
  addCargoArea: 'Add Section',
  editCargoArea: 'Edit Section',
  ShippingAreaNumber: 'Code',
  ShippingAreaName: 'Name',
  WhetherToEnable: 'In use',
  Pleaseenterrackcode: 'Please enter rack code',
  Examples: 'Examples: A1-1-01、00-01、1',
  pleaseEnterShippingAreaNumber: 'Please enter section code',
  pleaseEnterShippingAreaName: 'Please enter section name',
  checkStockGoods: 'Product',
  checkStockStatus: 'Status',
  checkStockDate: 'Date',
  aisle: 'Aisle',
  row: 'Row',
  Columns: 'Columns',
  Floor: 'Layer',
  pleaseEnterCapacity: 'Please enter capacity',
  PleaseSelectTheTargoarea: 'Plese select section',
  editCargoShelf: 'Edit Rack Information',
  ...enLocale,
};
export default en;
